### ISSUE TITLE
Interpolation tick overflows after disconnection

### ISSUE THREAD

**Issue by benknowles** [cBournhonesque/lightyear#276]
Hello,

I disconnected from a server and after a bit of idling got an overflow error related to the interpolation tick.

```
2024-04-27T21:35:22.717937Z  INFO lightyear::connection::netcode::client: client connection timed out
2024-04-27T21:35:22.718572Z  INFO lightyear::client::networking: Running OnDisconnect schedule
2024-04-27T21:35:22.718801Z  INFO lightyear::transport::webtransport::client_native: WebTransport connection closed. Reason: client requested disconnection.
```

```
thread 'Compute Task Pool (14)' panicked at C:\Users\User\.cargo\git\checkouts\lightyear-2cfb5e6660946fe3\a857c66\lightyear\src\client\prediction\prespawn.rs:329:25:
attempt to multiply with overflow
stack backtrace:
   0:     0x7ffeffc03e88 - std::backtrace_rs::backtrace::dbghelp64::tra
   ```
   
I'm not sure if this is a bug exactly. If a server disconnect happens, am I expected to despawn everything myself? Cuz I guess I haven't considered whether it's possible to resume an existing session, or what would happen to existing entities in the scene on a reconnect.

**Comment by cBournhonesque** [comment]
Thank you, yes I believe it's a bug!
`interpolation_tick` is incremented only as long as we stay connected to the server (it's a tick that is far enough in the past so that we should have received 2 server updates to interpolate between), while `tick` always gets incremented.

I need to:
- probably not run that system if the client is not connected
- add checked_diffs/sums to that operation

When the client gets disconnected from the server, the current behaviour is that I automatically despawn every entity that was replicated from the server (every entity with `Confirmed`/`Predicted`/`Interpolated`)
