### ISSUE TITLE
Show how bevy+lightyear can be used to deploy actual games

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#32]
My end goal is to be able to deploy a multiplayer web game (or if not web, with dedicated servers), with lobbies/arenas/matchmaking.

One potential solution for this is to integrate with Agones.

Pros:
- scalable
- bevy is abstracted: just needs to be a server container, which hooks up in the SDK for matchmaking, etc.
- rust client

**Comment by Nul-led** [comment]
Another good alternative would be running a [Rivet](https://github.com/rivet-gg) instance. Been working with them for some time now. Really good matchmaking they have imo.

**Comment by NathanFlurry** [comment]
Just saw this mention. There are a handful of Bevy games being built with Rivet, but they're all winging it since there's no official Bevy lib & networked example yet. We haven't had a chance to publish any Bevy demos yet.

I would love to help out on getting a demo together if possible. Happy to provide free hosting for demos if interested.

**Comment by cBournhonesque** [comment]
Yes, I've tried getting rivet to work, but at the time it was a bit painful because the docs were pretty sparse.
I ended up using Edgegap to get some demos up

**Comment by cBournhonesque** [comment]
People can now try https://github.com/RJ/bevygap
