### ISSUE TITLE
Still receiving inputs after a client disconnects

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#486]
I have a basic setup testing movement, .e.g

<img width="1027" alt="image" src="https://github.com/cBournhonesque/lightyear/assets/48108917/ecff80e4-7299-4f6f-9996-bd22041c9789">

Everything looks good but then when a client disconnects, there are no entities remaining.

I confirmed, seeing the server's inspector - There are no entities after the client leaves.

<img width="622" alt="image" src="https://github.com/cBournhonesque/lightyear/assets/48108917/78a27e4e-4ecf-4e43-8a70-616adc9d6e08">

But I still get inputs from those clients, despite them being disconnected/gone, causing this output:

<img width="1307" alt="image" src="https://github.com/cBournhonesque/lightyear/assets/48108917/2141efc6-2f83-4794-afa0-686ca6e48f99">

**Comment by cBournhonesque** [comment]
Interesting, you're using the native inputs, not leafwing, correct?

**Comment by simbleau** [comment]
Yeah

**Comment by cBournhonesque** [comment]
I fixed it here: https://github.com/cBournhonesque/lightyear/pull/496

However I might get rid of native inputs entirely and only use leafwing from now on. Both to reduce the maintenance burden, but also because some new features (predicting remote player inputs, input delay) are easier to do with leafwing
