### ISSUE TITLE
WASM: `client_send_interval: Duration::ZERO` causes heavy FPS drop/lag

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#487]
I made a full migration from WebRTC to WebTransport (using Lightyear) and noticed my FPS tanked from solid 60fps to ~20fps.

Ultimately, after much investigation, simply changing `client_send_interval: Duration::ZERO` to `client_send_interval: Duration::from_millis(100)` basically removed the FPS tanking and I have good performance again..

My guess is that this is because less throughput is being requested, essentially, but it does indicate that optimizing writes could help here?

Also, there's a tradeoff: By changing the send_interval to 100ms, I get pretty bad movement now because rollbacks are common.

**Comment by simbleau** [comment]
Hmm, I also lowered the network tick rate to 100ms instead of 60 times per second, to reduce simulation ticks. That seemed to help significantly and I could consider this issue a non-issue upon further thought.

**Comment by simbleau** [comment]
@cBournhonesque do you want me to close this issue or keep it open to track optimizing the  performance bottlenecks?

**Comment by cBournhonesque** [comment]
How often were you sending packets with WebRTC vs with lightyear? (for both client->server and server->client)

In your second message you're saying you changed the server->client send rate from 60Hz to 10Hz?


Also I believe that `client_send_interval` has to be `Duration::ZERO` for prediction/input-handling to work correctly.
The reason is that the client is running RTT/2 ahead of the server (just enough ahead for the client inputs for tick T to arrive to the server when the server runs tick T). If you don't send client inputs every tick, then a lot of client inputs might be missed, which will cause a lot of rollbacks.

The solution is probably to make the client run `RTT/2 + client_send_interval` ahead of the server, so that in all cases the server will have access to all the client inputs. Maybe that warrants its own separate issue
