### ISSUE TITLE
Game server can't detect missing/late player inputs

### ISSUE THREAD

**Issue by RJ** [cBournhonesque/lightyear#492]
In [server/input/leafwing.rs `update_action_state`](https://github.com/cBournhonesque/lightyear/blob/main/lightyear/src/server/input/leafwing.rs#L190) the server calls `input_buffer.pop(tick)` for the current tick, and assigns the resulting input to the ActionState component.

In doing so, it removes the input for the current `tick` from the `InputBuffer`. 

If no such input existed, possibly due to the client's packet arriving too late, it assigns a default ActionState.

The game server's system that handles player input then has no way to detect if an input was missing. It can't tell if the `ActionState` is empty because the player wasn't pressing a key, or if a default action state was assigned due to a missing input from a late packet.

### Possible solutions

**1** 
change `pop(tick)` to (eg) `pop_before(tick)` which leaves the input for `tick` in the buffer?

this would allow the game server to check `InputBuffer::get(tick).is_some()`

**2** 
player controlled entities on the server get an additional component, something like `ConnectionHealth` with a bool saying if the current input is missing

**3**
remove `ActionState` for ticks with no input? would complicate game systems a little, but intention clear 

**4**
something else, perhaps related to the client-side half of this issue too, which is more complex due to predicted inputs.

**Comment by cBournhonesque** [comment]
| If no such input existed, possibly due to the client's packet arriving too late, it assigns a default ActionState.

FYI this behaviour has changed, it now uses the most recently used ActionState (i.e. it considers that the remote player keeps playing the same input).

My preferred solution would maybe be to add a function `handle_missing_input(buffer: &InputBuffer, current_tick: Tick, last_present_tick: Tick)` to the `LeafwingUserAction`, that every `Actionlike` would have to implement.
There would be a default implementation which would just re-use the latest received input.

For more complex implementations (we don't want to re-click buttons, we want to go back to the middle of the joystick, etc.), the user can override the default impl. What do you think?

**Comment by RJ** [comment]
consider the case where you want to reduce forward speed towards zero as the number of missing inputs increases. In practice this could mean reducing the force applied to the player object by some amount based on how many ticks of predicted inputs are being used, with `forward=true` in the last known input.

implementing `handle_missing_input` would allow you to pick what ActionState to use as a prediction, but would it be possible to know, in the game's system that handles the input, whether the input was missing or predicted from N frames ago?

**Comment by RJ** [comment]
i like the idea to allow pluggable strategies to decide what the ActionState should be by looking in the input buffer when there are missing inputs. that logic is (distractingly) living at the top of my main forces based movement system for now.

however to be flexible enough to support things like decaying forces based on number of missed inputs, i need to know how many ticks stale the input is, since my inputs for eg `fordward` is a bool, not a float. So I can't encode decay into the ActionState.

**Comment by cBournhonesque** [comment]
So `handle_missing_input(buffer: &InputBuffer, current_tick: Tick, last_present_tick: Tick) -> ActionState` would work in this situation, right?

You have the staleness via `current_tick - last_present_tick`

**Comment by RJ** [comment]
wouldn't work, unless i don't understand something.. 

you can calculate the staleness in the `handle_missing_input` function, but how do you pass that value to the game's input handling system? 

```rust
fn custom_handle_missing_input(buffer: &InputBuffer, current_tick: Tick, last_present_tick: Tick) -> ActionState {
  buffer.get(last_present_tick).unwrap() // whatever logic here 
}

fn my_movement_system(q: Query<(&ActionState, &mut Forces), With<Player>>) {
 for (action, mut forces) in q.iter() {
  let speed = 100.0;
  if action.pressed(Forward) {
    forces.apply_force(Vec2::Y * speed);
  }
 }

```

eg. how can i decay the movement `speed` from 100 to 50 if inputs are 3 ticks old?

**Comment by RJ** [comment]
I could put a skip(serde) field into Player actions to store it in 🤔

**Comment by cBournhonesque** [comment]
Ah i thought the `ActionState` itself would have a reduced speed, I didn't get that the inputs are booleans but how you handle them is not.
I think you can access this information from the `InputBuffer` directly, no?

I get that you're saying it has ergonomic concerns (what is the point of using `ActionState` if you have to query the `InputBuffer` every time), but I think 95% of users/use-cases would only care about accessing the `ActionState` and would use the default missing input behaviour (reusing the previous input). That's why I'm a bit hesitant to introduce a more complicated wrapper around `ActionState` when most cases don't need it.

For more complicated cases, you can just query directly the `InputBuffer`. 
Or does this not work? I saw you mentioned that you needed
> 1
change pop(tick) to (eg) pop_before(tick) which leaves the input for tick in the buffer?

**Comment by RJ** [comment]
fair enough, definitely a more niche case.. it'll work fine on the client to check the input_buffer directly, but not on the server since the actionstate for the current frame gets popped out the input buffer during assigning to the ActionState component.

**Comment by cBournhonesque** [comment]
Would something like this work? https://github.com/cBournhonesque/lightyear/pull/499

**Comment by RJ** [comment]
yes, #499 will work - server's system can do input_buffer.get(tick) to check, if you only pop(tick -1) 👍
