### ISSUE TITLE
TooLarge errors with high throughput

### ISSUE THREAD

**Issue by DarkZek** [cBournhonesque/lightyear#565]
When sending too many large messages both the client and server can experience forever looping TooLarge errors.
Reproduction using the simple_box example https://github.com/DarkZek/lightyear/tree/large-packets just move around and press m a couple times to send the messages.
Debugging conversation on the Bevy discord: https://discord.com/channels/691052431525675048/1189344685546811564/1269488823558213694
Video link: https://cdn.discordapp.com/attachments/1189344685546811564/1269181391900508292/Screen_Recording_2024-08-03_at_6.31.54_PM.mov?ex=66afc988&is=66ae7808&hm=6f9a48cc32d9b79a4294e98e3085cc0be4201372482a2ed6ee57d1a9c464339d&

**Comment by cBournhonesque** [comment]
The `TooLarge` error was due to the MTU config of QUIC (in quinn).
Their MTU was set to 1200 bytes whereas the netcode packets can reach 1300 bytes.
In practice it wasn't an issue because they do MTU discovery to increase their MTU is packets higher than the MTU have been successfully transmitted, but I guess it breaks down in high-throughput situations.


Fixed with https://github.com/cBournhonesque/lightyear/pull/567, where I manually set the QUIC MTU to 1300 bytes.

**Comment by cBournhonesque** [comment]
As for the box jumping around; it's because most of the bandwidth is being used to send the message chunks instead of the replication updates and inputs. I explained on discord how you can use the `PriorityManager` to make sure that replication updates have a higher priority than the chunks:
https://discord.com/channels/691052431525675048/1189344685546811564/1269689613073776792

See this section of the book: https://cbournhonesque.github.io/lightyear/book/concepts/advanced_replication/bandwidth_management.html
