### ISSUE TITLE
`bevy_ecs::world: error[B0003]` when running `OnDisconnect` schedule

### ISSUE THREAD

**Issue by SK83RJOSH** [cBournhonesque/lightyear#590]
Hello again!

We've run into an issue with our odd use case again, which is that a client owned entity:
```rust
commands.spawn((
    OwnedEntity {
        OwnerId(local_client_id),
        Replicate {
            group: ReplicationGroup::new_id(local_client_id.to_bits()),
            ..default()
        }
    },
));
```

Which is replicated by the server:
```rust
fn replicate_owned_entities(
    mut commands: Commands,
    mut owned_entities_reader: EventReader<ComponentInsertEvent<OwnerId>>,
) {
    for event in owned_entities_reader.read() {
        info!("received owned entity: {:?}", event);
        let client_id = event.context();
        let entity = event.entity();

        if let Some(mut e) = commands.get_entity(entity) {
            e.insert(Replicate {
                target: ReplicationTarget {
                    target: NetworkTarget::AllExceptSingle(*client_id),
                },
                sync: SyncTarget {
                    prediction: NetworkTarget::None,
                    interpolation: NetworkTarget::AllExceptSingle(*client_id),
                },
                controlled_by: ControlledBy {
                    target: NetworkTarget::Single(*client_id),
                    ..default()
                },
                group: ReplicationGroup::new_id(client_id.to_bits()),
                ..default()
            });
        }
    }
}
```

Doesn't get cleaned up correctly on the owning client when disconnecting:
```
2024-08-13T08:17:48.411008Z  INFO lightyear::client::networking: Running OnDisconnect schedule
2024-08-13T08:17:48.412883Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity Entity { index: 54, generation: 2 } because it doesn't exist in this World. See: https://bevyengine.org/learn/errors/#b0003
```

Which then leads to the owned entity getting replicated back to the server if that client connects again in the future.

**Comment by cBournhonesque** [comment]
Hi!
I'm not sure I fully understand.
- Client C1 owns entity E1 and replicates it to the server
- Server S receives E1, spawns ES1 and replicates it to other players
- C1 disconnects; since E1 is 'controlled' by C1, S despawns it for everyone
- the warning on C1 might be because C1 somehow already despawned the entity (maybe in one of your systems), and receives another message from S telling it to despawn it?

But then you say `Which then leads to the owned entity getting replicated back to the server if that client connects again in the future.`
You're saying that when C1 connects again, E1 still exists and gets replicated to S?

1) can you confirm that E1 still exists on the client even after disconnection?

Actually it might be because I maintain an entity mapping from Sender -> Receiver, and the receiver is responsible to doing the mapping. So when the server sends a message to C1 to tell it to despawn the entity, it uses ES1, which doesn't get converted to E1 because in your case the client is the sender.

I have an issue open about this problem: https://github.com/cBournhonesque/lightyear/issues/553
(i.e. that entity mapping only works from sender -> receiver, not from receiver -> sender)

In your case, I wouldn't rely on a server message to despawn the entity anyway, since you might get disconnected before receiving the message 'DespawnEntity' from the server. I would a system `on_disconnect` that despawns any entity with the `OwnerId` component and that runs in `OnEnter(NetworkingState::Disconnected)`

**Comment by cBournhonesque** [comment]
This should be fixed on `main` since I improved how entity mapping is done

**Comment by SK83RJOSH** [comment]
Heya, the warning is indeed fixed, but we're going to do a deep dive on the behavior here next week just to make sure we understand what the current behavior is/if there's still an underlying issue here.

I'll leave this open for now and follow up with our findings (or lack thereof) asap. 🙂

**Comment by cBournhonesque** [comment]
Sure, i can give you a small explanation of my current understanding

- Client 1 spawns an entity `E1` and replicates to the server S.
- the receiver (here the server) spawns a corresponding entity `E2` and maintains an internal mapping from local=`E2` to remote=`E1`
- the server may replicate this entity to other clients, for example client 2 spawns `E3` and maintains an internal mapping from local=`E3` to remote=`E2`
- client 1 disconnects: the server sees that `E2` was controlled by client 1, and despawns it. The despawn is replicated to clients according to the `ReplicationTarget`. 
  - here I'm a bit confused. Normally the `ReplicationTarget` would exclude client 1 so client 1 would NOT get notified of the despawn at all. It's possible that in your case the entity is still despawned because of [this](https://github.com/cBournhonesque/lightyear/blob/d2dbbf3a5ce7218d3b9f16b2531b56167cc9d190/lightyear/src/client/networking.rs#L408-L408): on disconnection a client despawns all its Predicted/Interpolated/Replicated entities (replicated means 'replicated from a remote peer'). If `ReplicationTarget` included client 1, the server would map `E2` to `E1` (this is the change to entity mapping that I was referring to, the sender of a message can now also apply entity mapping from the local world to the remote world if such a mapping exists) and send it to client 1. Client 1 would receive it (if it receives it before actually disconnecting) and despawn the entity.
  - the server sends a message to client 2 that `E2` is despawned. Client 2 receives the message, maps `E2` to its local entity `E3` and despawns it

**Comment by SK83RJOSH** [comment]
Alrighty, we got around to looking at this in further detail, and think we have a grasp on things now. So going to close this out as to not litter your issues. 😄

**Comment by sQu1rr** [comment]
@cBournhonesque I get the same error message when running the simple_box example, after I press the disconnect button. How do I get around it? It seems like it may break something by dispawning incorrect entities.
